# Generated by Django 2.2 on 2023-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=20)),
                ('bodytext', models.TextField()),
                ('bgcolor', models.CharField(max_length=20)),
                ('textcolor', models.CharField(max_length=20)),
            ],
        ),
    ]
