# Generated by Django 2.2 on 2023-12-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231229_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='travel',
            new_name='travels',
        ),
    ]
