# Generated by Django 2.2 on 2023-12-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231229_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='authors',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
