# Generated by Django 2.2 on 2024-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231229_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='travels',
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
